name:                depsolver
version:             0.1.0.0
github:              "ukc-co663/dependency-solver-2019-GuiltyDolphin"
license:             BSD3
author:              "Ben Moon"
maintainer:          "bgm3@kent.ac.uk"
copyright:           "2019 Ben Moon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Dependency solver for CO663 Assessment 1
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ukc-co663/dependency-solver-2019-GuiltyDolphin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - json
  ghc-options:
  - -Werror
  - -Wall

executables:
  depsolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    dependencies:
    - depsolver

tests:
  depsolver-test:
    main:                Spec.hs
    source-dirs:         test/hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - depsolver
    - hspec
    - QuickCheck
    - QuickCheck-GenT
    - filemanip
    - filepath
    - mtl
